//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontMeasure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_GearFront
    {
        public System.DateTime Insert_Time { get; set; }
        public decimal Work_Date { get; set; }
        public int Work_No { get; set; }
        public string GearNo_Front { get; set; }
        public string GearNo_4WD { get; set; }
        public string Part_Name { get; set; }
        public Nullable<double> FGear_G4_Min { get; set; }
        public Nullable<double> FGear_G4_Val { get; set; }
        public Nullable<double> FGear_G4_Max { get; set; }
        public Nullable<double> FGear_G2_Min { get; set; }
        public Nullable<double> FGear_G2_Val { get; set; }
        public Nullable<double> FGear_G2_Max { get; set; }
    }
}
